### ISSUE TITLE
dramamask + biggerlobby issue

### ISSUE THREAD

**Issue by TheRealMrKam** [Henit3/DramaMask#1]
Hello, I found a bug between the version 1.1.0 of  DramaMask ( version 1.0 don't have this bug, just saw you published a new version but haven't tried it yet, maybe it's already fixed, in that case sorry for bothering you) and biggerlobby.

When i go on experimentation they all go (sliding, no walking animation) in this corner close to the ship and stay there. 

![image](https://github.com/Henit3/DramaMask/assets/154998012/6e4a2755-8061-47b3-93cc-473962f0dde6)

**Comment by Henit3** [comment]
Thanks for raising this; I don't usually play with biggerlobby but I think I know what could be causing the issue. I'll try address this in the next patch update.

**Comment by TheRealMrKam** [comment]
Thank you :)

**Comment by Henit3** [comment]
This should be fixed in the latest version 1.1.3. Let me know if it's still causing issues, though I have tested it locally without problems.
