### ISSUE TITLE
Ending the day with the mask on bugs your character inventory

### ISSUE THREAD

**Issue by Regnareb** [Henit3/DramaMask#2]
If you get out of the planet on your ship with the mask on your face, the mask disappears but still shows up in your inventory.
Then you can't interact with objects until you die.

In case it is because of an incompatibility with other mods, the Thunderstore code was 018e7d75-4829-7076-bfd1-820704562458

Thanks for this mod, I am eager to test it

**Comment by Regnareb** [comment]
It occurred on version 1.2.0 right before you updated the mod to 1.2.1. 
I don't know if your patch was related to this bug, I don't think it is but I have MoreEmote installed.

**Comment by Henit3** [comment]
Thanks for reporting this, should help replicate this easily. It's a bug to do with the mod itself, shouldn't be any incompatibilities. 1.2.1 would not have fixed this, but I will try to resolve this soon for the next release (1.2.2).

**Comment by Henit3** [comment]
It should be patched as of 1.2.2, please let me know if you still run into the same problems, though testing locally seems to show this being fixed (as well as some other related issues).
