### ISSUE TITLE
[Bug] "Base Drama Spawn Chance" doesn't seem to work

### ISSUE THREAD

**Issue by JohnMetroid** [Henit3/DramaMask#4]
set the slider to various values between 0 and 1000, but never saw a Drama mask for over an hour.  Immediately forced Drama masks to spawn with the other option by specifying moons.

**Comment by Henit3** [comment]
I've checked the spawnable items and increased the slider like you did, finding Drama masks as I'd expect.

I'm now aware I haven't made it obvious that it only spawns on moons with normal masks:
- Assurance (very low chance)
- Rend (low/medium chance)
- Dine (low/medium chance)
- Titan (low/medium chance)
- Modded (low/medium chance)

Perhaps you didn't go to one of these moons, or if you did, were unlucky.

Alternatively, this could be a compatibility issue with one of your other mods.

Could you let me know which of these is the case, and drop your thunderstore profile code in a reply in case you think it is a compatibility issue?

**Comment by JohnMetroid** [comment]
Yeah, I was on planets with no base mask drop rate -- because it was never mentioned that it modified the base drop rate of other masks.  It's explicitly called the Drama mask drop rate and none of this is mentioned in your documentation.

If it clearly isn't intended to function as a base spawn rate variable, it really needs to be renamed and given an appropriate description.  What a colossal, avoidable waste of time.  Yikes.

**Comment by Henit3** [comment]
I'm sorry to hear this was a nuisance, I'm going to add a fuller description of the default spawn rates of Drama mask in the ReadMe as part of the FAQ I'd planned earlier, and add it in the description of the config for the next patch alongside a planned bug fix 

To clarify, this config name should have been called a Base Drama Mask Spawn "Multiplier" to align with its effects, and it only uses other mask spawn rates as a reference; it does not modify those.

I'll close after the next patch resolves this.
