### ISSUE TITLE
Drama Mask and Spray Paint Shaking

### ISSUE THREAD

**Issue by VirusTLNR** [Henit3/DramaMask#5]
Hi,

love your mod, but in a recent patch, it seems to have broken shaking the spray paint for me

i have checked the keybinds for the drama mask, did you recently set Q as the keybind? if so this is likely the issue as Q is how you shake the spray paint

i will change the keybind for my group, but i figured i should let you know this is occuring as i assume spray paint should still be able to be shaken and that the keybind should only be active when a mask is in the hands of the player.

**Comment by Henit3** [comment]
Hey, this was reported as an issue in 1.3.2 but should have been resolved in 1.3.3.
For context, it used to be an incompatibility with MoreCompany introduced in 1.3.0.

Could you make sure you are on the latest update and check again?
If it still persists, could you reply with your thunderstore profile code so I can replicate the issue and check for any other incompatibilities.

Edit: It seems an update to InputUtils managed to break this again, I'll fix probably tomorrow evening or so.
Thanks for reporting the issue!

**Comment by Henit3** [comment]
Took less time than I thought, should be resolved in version 1.3.4, which I've just released. Let me know if you still run into this issue!

**Comment by Henit3** [comment]
So I looked at the code I just added and there's flipped logic so there should be a new bug where rebinding one of them will not work. This will have to be fixed tomorrow evening for sure.

**Comment by VirusTLNR** [comment]
thanks for the feedback, i knew something had changed, was just baffled!, let me know when you patched and i will check as soon as i see!

**Comment by VirusTLNR** [comment]
on my profile for testing this issue, i can rebind keys, and i can shake the can again, so seems fixed!

018ee224-7dc1-d9a0-aec2-bc8dc5817515

it has drama mask 1.3.4 installed.

thanks!
